-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."AuthClaims"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "memberId" integer NOT NULL,
    "authId" integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."AuthRoles"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "roleDef" character varying(10) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."CorpTypes"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "corpDef" character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."Genders"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "genderDef" character varying(10) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."JobStatus"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "statusDef" character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."MemberTypes"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "memberDef" character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."Members"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "nationalId" character varying(11) NOT NULL,
    name character varying(50) NOT NULL,
    "lastName" character varying(50) NOT NULL,
    gender smallint NOT NULL,
    birthdate date NOT NULL,
    phone character varying(10) NOT NULL,
    mail character varying(100) NOT NULL,
    password character varying(9999) NOT NULL,
    "registerDate" date NOT NULL,
    "memberType" smallint NOT NULL,
    "jobStatus" smallint,
    "corpName" character varying(150),
    "corpType" smallint,
    active smallint NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public."AuthClaims"
    ADD FOREIGN KEY ("authId")
    REFERENCES public."AuthRoles" (id)
    NOT VALID;


ALTER TABLE public."AuthClaims"
    ADD FOREIGN KEY ("memberId")
    REFERENCES public."Members" (id)
    NOT VALID;


ALTER TABLE public."Members"
    ADD FOREIGN KEY ("corpType")
    REFERENCES public."CorpTypes" (id)
    NOT VALID;


ALTER TABLE public."Members"
    ADD FOREIGN KEY (gender)
    REFERENCES public."Genders" (id)
    NOT VALID;


ALTER TABLE public."Members"
    ADD FOREIGN KEY ("jobStatus")
    REFERENCES public."JobStatus" (id)
    NOT VALID;


ALTER TABLE public."Members"
    ADD FOREIGN KEY ("memberType")
    REFERENCES public."MemberTypes" (id)
    NOT VALID;

END;